### ISSUE TITLE
Fatal error after composer update 

### ISSUE THREAD

**Issue by Biiru** [punktDe/sentry-flow#16]
Hello, 

I just did a composer update from my Neos (7.3.5) project and I have this error from this package

`PHP Fatal error:  Uncaught Neos\Flow\Error\Exception: Warning: Declaration of PunktDe\Sentry\Flow\Handler\ExceptionHandlerTrait::echoExceptionCli(Throwable $exception): void should be compatible with Neos\Flow\Error\AbstractExceptionHandler::echoExceptionCli(Throwable $exception, bool $exceptionWasLogged) in /var/www/gabwebcms.alloboissons.ch/Packages/Application/PunktDe.Sentry.Flow/Classes/Handler/DebugExceptionHandler.php line 27 in /var/www/gabwebcms.alloboissons.ch/Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php:81
Stack trace:
#0 /var/www/gabwebcms.alloboissons.ch/Packages/Application/PunktDe.Sentry.Flow/Classes/Handler/DebugExceptionHandler.php(13): Neos\Flow\Error\ErrorHandler->handleError()
#1 /var/www/gabwebcms.alloboissons.ch/Packages/Libraries/composer/ClassLoader.php(571): include('/var/www/gabweb...')
#2 /var/www/gabwebcms.alloboissons.ch/Packages/Libraries/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 [internal func in /var/www/gabwebcms.alloboissons.ch/Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php on line 81
`

There is the package list updated, maybe it can help

  - Upgrading composer/composer (2.3.5 => 2.3.7)
  - Upgrading flowpack/elasticsearch (5.0.4 => 5.0.5)
  - Upgrading laminas/laminas-code (4.5.1 => 4.5.2)
  - Upgrading neos/cache (7.3.5 => 7.3.6)
  - Upgrading neos/eel (7.3.5 => 7.3.6)
  - Upgrading neos/error-messages (7.3.5 => 7.3.6)
  - Upgrading neos/flow (7.3.5 => 7.3.6)
  - Upgrading neos/flow-log (7.3.5 => 7.3.6)
  - Upgrading neos/fluid-adaptor (7.3.5 => 7.3.6)
  - Upgrading neos/http-factories (7.3.5 => 7.3.6)
  - Upgrading neos/kickstarter (7.3.5 => 7.3.6)
  - Upgrading neos/utility-arrays (7.3.5 => 7.3.6)
  - Upgrading neos/utility-files (7.3.5 => 7.3.6)
  - Upgrading neos/utility-mediatypes (7.3.5 => 7.3.6)
  - Upgrading neos/utility-objecthandling (7.3.5 => 7.3.6)
  - Upgrading neos/utility-opcodecache (7.3.5 => 7.3.6)
  - Upgrading neos/utility-pdo (7.3.5 => 7.3.6)
  - Upgrading neos/utility-schema (7.3.5 => 7.3.6)
  - Upgrading neos/utility-unicode (7.3.5 => 7.3.6)
  - Upgrading nikic/php-parser (v4.13.2 => v4.14.0)
  - Upgrading symfony/polyfill-ctype (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-iconv (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-grapheme (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-idn (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-normalizer (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-php80 (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-php81 (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-uuid (v1.25.0 => v1.26.0)
  - Upgrading webmozart/assert (1.10.0 => 1.11.0)

Thanks a lot for your time and if I can help, don't hesitate !

**Comment by daniellienert** [comment]
@Biiru - thanks for reporting. Should be fixed with the latest release.
