### ISSUE TITLE
Make Sentry client option`send_default_pii` available via settings

### ISSUE THREAD

**Issue by TheLalaMan** [punktDe/sentry-flow#18]
We wanted to use the inbound filters on a Sentry cloud instance to filter by IP address and discovered that the package does not send the IP at all.

It would be helpful to be able to configure this via settings, the Sentry client needs the option `send_default_pii` set to `true`. Then the IP address is sent to the Sentry cloud instance and the filters work.

**Comment by daniellienert** [comment]
Thanks a lot @TheLalaMan
